### ISSUE TITLE
所有包都按书里说的安装成功，但是运行还是有错误。

### ISSUE THREAD

**Issue by Neo01010** [duoergun0729/1book#14]
![image](https://user-images.githubusercontent.com/15312660/35546595-d446a35c-05af-11e8-97b4-ebbcd6865b1c.png)

**Comment by Neo01010** [comment]
环境是python 2.7

**Comment by shixiangbupt** [comment]
![default](https://user-images.githubusercontent.com/5387481/43937903-37681cb6-9c93-11e8-9397-a93c53be3c79.png)
没有问题的，jupyter中用的python3.4
