### ISSUE TITLE
对于 7-3.py 中的代码有一处疑惑

### ISSUE THREAD

**Issue by FoolMitAh** [duoergun0729/1book#3]
line 37:
webshell_bigram_vectorizer = CountVectorizer(ngram_range=(1, 1), decode_error="ignore",
                                        token_pattern = r_token_pattern,min_df=1)

line 45: 
wp_bigram_vectorizer = CountVectorizer(ngram_range=(2, 2), decode_error="ignore",
                                        token_pattern = r_token_pattern,min_df=1,vocabulary=vocabulary)

在对黑样本的特征化过程中，用的是1-gram，提取出的 vocabulary 也是 1-gram

但是在白样本的特征化中，使用的仍然是 2-gram，提取出的 字符串 不可能出现在 vocabulary 中啊..
白样本的特征向量全都为 [0 0 0 ... 0 0 0]

**Comment by duoergun0729** [comment]
笔误 应该都是1-gram
