### ISSUE TITLE
P132中倒数第四行勘误

### ISSUE THREAD

**Issue by Long80A** [duoergun0729/1book#7]
P132，倒数第四行，原文："from sklearn.cluster import K-Means"，纠正为："from sklearn.cluster import KMeans"

**Comment by Long80A** [comment]
P44，倒数第四行，原文："from sklearn.cluster import K-Means"，纠正为："from sklearn.cluster import KMeans"

**Comment by duoergun0729** [comment]
tks

**Comment by duoergun0729** [comment]
已经更新github上的勘误
